---
title: Curriculum  Analysis from Winter of 2018 to Spring of 2023
author: by Juliana Trujillo Mesa & Nils Midtun 
output: github_document
---

## Summary

Our team created a College of the Atlantic (COA) Curriculum Analysis from winter 2018 to spring 2023. Creating these visualizations matters because the Academic Affairs Committee (AAC) & other stakeholders at COA need to understand the current situation to make decisions impacting curriculum practices, instructor hiring, & ultimately, students' career paths. Some relevant variables include department, graduation requirements, instructor status, lab fees, class level, prerequisites & class size. Our dataset came together by getting the raw data from the Registrar which our Computer Science professor Laurie Baker arranged in the first version of the dataset. Then, our team expanded the dataset in collaboration with Laurie to add columns from the course descriptions (written by professors) and a column on instructor status, which we got from the Academic Services Administrator. 

Our guiding question for this project was, "How well are the course offerings at COA meeting students' needs?" To address the answer, we chose subsequent questions to address different aspects & variables of the answers. First, we asked, "How are COA course offerings distributed across resource areas?" and used a horizontal bar plot showing the proportional distribution of courses by department for each term. HS consistently comprises 30% or more of the courses offered, while ES & ADS have similar distributions. 

Our second question was, "How well are COA course offerings meeting students' graduation requirement needs?" To answer, we created a line graph showing the number of courses available to meet graduation requirements over the years. The visualization shows that the class offerings give the greatest opportunity to meet HS requirements, followed by ES & ADS. It is important to note that classes that met more than one requirement were counted twice as opportunities to meet each requirement. We added a second line graph to show the same data in the term scale. Significant peaks and drops in class offerings are observed across terms for all the requirements.
The third question was, "How many courses are different instructors teaching proportionally?" We created a horizontal bar plot showing the proportional distribution of classes taught by different instructor statuses per term, faceted by resource area. This visualization showed that Permanent Faculty primarily teach ES classes while only some ED classes are.

Our fourth question asked, "What are the Lab fees in the different resource areas?" To answer, we created a box plot showing the distribution of lab fees in USD by department. The visualization suggests that AD, ES & MD have the most considerable lab fees and distribution. HS & ED have the lowest lab fees, yet HS has higher outliers. 
Our final question was, "How does class size vary among resource areas?" Through a violin plot, we showed the class size distribution by department. The visualization shows how ES has the most variation & higher outliers. Most class sizes range from 12 - 17 spaces.

Our team decided that making conclusions to our general questions was risky since this was a preliminary data analysis with limitations. Some limitations of our project were time constraints, missing the official count of enrolled students per class, NAs in certain variables, and missing data for the fall of 2017 to complete visualizations from the last six academic years. Still, this project was an illuminating first step to go beyond our perceptions of the curriculum and see the objective reality. We need more ore data and visualizations. In the future, engaging with predictions by visualizing academic policy change scenarios could also enhance our decision-making processes. Even more, creating a work-study position for COA's data analysis would improve decision-making processes across vital sections of our college. 

```{r load-data, echo = FALSE}
glimpse(coa_courses3)
```


## Presentation

Our presentation can be found [here](https://www.canva.com/design/DAFz_ie9YQA/wZ_kQlDVcwf1hfWHrzoXFA/edit?utm_content=DAFz_ie9YQA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).

## Data 

The data of this project came primarily from Krystal Meservey, the Registrar, and subsequently from Lothar Holzke, the Academic Services Administrator. The dataset was mainly arranged by Laurie Baker, the Computer Science, in collaboration with Juliana Trujillo and Nils Midtun from the class of 2024. 

